seed: 1919
save: "./checkpoint/mqar-norm-attention-conv"
dataset:
  name: "MQAR"
  _name_: "mqar"
  input_seq_length: 512
  num_kv_pairs: 64
  data_dir: ""
  fixed_size: True
train:
  total_steps: 40_000
  batch_size: 64
  lr: 0.001
  wd: 0.1
  eval_every: 200
  stop_criterion: 0.99 # accuracy
  cosine_anneal: True
  param_group: ~
  warmup: 4_000
model:
  # task specific dims
  input_dim: 1
  output_dim: 8_192
  # backbone model
  layer: "transformer"
  attention_fn: "norm-attention"
  mode: "attention"
  norm_fn: "softplus"
  approx_fn: "elu"  # could try none
  scale_B: True
  offset: True
  offset_init: "exp"
  learn_A: False # set this to False!
  dim_conv: 4
  use_flash: False
  num_layers: 2
  hidden_dim: 128
  state_dim: 128
  num_heads: 1
  att_dropout: 0.0
  norm: "layer"
  # embedding & positional embedding
  embedding: True
  vocab_size: 8_192
  max_pos_embed: 0
  # mlp
  mixer: "none"
  mixer_dim: 128
  # global dropout rate
  dropout: 0.1
  # classifier
  classifier: False
  pooling: "mean"
  # use dual classification
  dual: False
