seed: 1919
save: "./checkpoint/models/imdb-s4"
dataset:
  name: "IMDB"
  _name_: "imdb"
  fixed_size: False
  data_dir: ""
train:
  num_epochs: 30
  batch_size: 6
  lr: 0.0005
  wd: 0
  ssm_lr: 0.001
  lr_min: 0.0000001
  reduce_factor: 0.5
  lr_patience: 5
  warmup: 10
  cosine_anneal: True
model:
  layer: "s4"
  dt_min: 0.001
  dt_max: 0.1
  num_layers: 4
  activation: "full_glu"
  input_dim: 135
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  dropout: 0
  norm: "batch"
  pooling: "mean"
  ssm_lr_vars: [ "Lambda_re", "Lambda_im", "P", "B", "log_step" ]
  prenorm: True
  dual: False
