seed: 1919
save: "./checkpoint/imdb-mamba2"
dataset:
  name: "IMDB"
  _name_: "imdb"
  fixed_size: False
  data_dir: "" 
train:
  num_epochs: 30
  batch_size: 6
  lr: 0.0005
  wd: 0.01
  warmup: 5
  cosine_anneal: True
  param_group: ~
model:
  layer: "mamba"
  version: "mamba2"
  num_layers: 4
  num_heads: 4
  input_dim: 1
  output_dim: 2
  hidden_dim: 128
  state_dim: 64
  conv_dim: 4
  expansion: 1
  dropout: 0.0
  glu: True
  norm: "layer"
  dual: False
  prenorm: True
  pooling: "mean"
  embedding: True
  token_embedding: True
  vocab_size: 134
  max_pos_embed: 4096


