seed: 1919
save: "./checkpoint/cifar-10-lin-attention-conv"
dataset:
  name: "CIFAR-10"
  _name_: "cifar"
  grayscale: True
  tokenize: True
train:
  num_epochs: 50
  batch_size: 50
  lr: 0.0002
  wd: 0.0
  warmup: 5
  param_group: ~
model:
  # task specific dims
  input_dim: 1
  output_dim: 10
  dim_conv: 4  
  # backbone model
  layer: "transformer"
  attention_fn: "lin-attention"
  num_layers: 6
  hidden_dim: 512
  state_dim: 64
  num_heads: 4
  att_dropout: 0.2
  norm: "layer"
  # embedding & positional embedding
  # WARNING: make sure to set dataset.tokenize to True
  embedding: True
  vocab_size: 256 # discrete byte inputs
  max_pos_embed: 1024 # 0 means no positional embedding; otherwise length of input
  # mlp
  mixer: "mlp"
  mixer_dim: 128
  # global dropout
  dropout: 0.3
  # classifier
  classifier: True
  pooling: "mean"
  # use dual classification
  dual: False
