seed: 1919
save: "./checkpoint/listops-sm-attention"
dataset:
  name: "LISTOPS"
  _name_: "listops"
  data_dir: "./lra_release/listops"
  fixed_size: False
train:
  num_epochs: 50
  batch_size: 8
  lr: 0.0002
  wd: 0.1
  warmup: 5
  param_group: ~
model:
  # task specific dims
  input_dim: 1
  output_dim: 10
  # backbone model
  layer: "transformer"
  attention_fn: "sm-attention"
  num_layers: 6
  hidden_dim: 128
  state_dim: 64 #64
  num_heads: 4
  att_dropout: 0.1
  norm: "layer"
  # embedding & positional embedding
  embedding: True
  vocab_size: 18
  max_pos_embed: 2048
  # mlp
  mixer: "mlp"
  mixer_dim: 256
  # global dropout rate
  dropout: 0.1
  # classifier
  classifier: True
  pooling: "mean"
  # use dual classification
  dual: False
