seed: 1919
save: "./checkpoint/listops-lru"
dataset:
  name: "LISTOPS"
  _name_: "listops"
  data_dir: "./lra_release/listops"
  fixed_size: False
train:
  num_epochs: 50
  batch_size: 50
  lr: 0.01
  wd: 0.05
  ssm_lr: 0.01
  lr_min: 0.0000001
  reduce_factor: 0.5
  lr_patience: 5
  warmup: 5
  cosine_anneal: True
model:
  layer: "lru"
  r_min: 0.9
  r_max: 0.99
  dt_min: 0.001
  dt_max: 0.1
  num_layers: 6
  activation: "full_glu"
  input_dim: 20
  output_dim: 10
  hidden_dim: 128
  state_dim: 64
  dropout: 0
  norm: "batch"
  pooling: "mean"
  ssm_lr_vars: [ "Lambda_re", "Lambda_im", "P", "B", "log_step" ]
  prenorm: True
  dual: False
